const PDFDocument = require('pdfkit');

module.exports = (data, res) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  doc.pipe(res);

  doc.fontSize(20).text('Your Budget Summary (PDF)', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'right' });
  doc.moveDown();

  // Helper function to format amount stably as "Rs. [Amount]"
  const formatAmount = (amount) => {
    const formattedNumber = Number(amount || 0).toFixed(2);
    const sanitizedNumber = formattedNumber.replace(/[^0-9.]/g, ''); 
    return `Rs. ${sanitizedNumber}`;
  };

  doc.fontSize(14).text('Summary', { underline: true });
  doc.moveDown(0.2);
  doc.fontSize(12).text(`Total Income: ${formatAmount(data.totalIncome)}`);
  doc.text(`Total Expenses: ${formatAmount(data.totalExpenses)}`);
  doc.text(`Balance: ${formatAmount(data.balance)}`);
  doc.moveDown();

  // Income list
  doc.fontSize(14).text('Income List', { underline: true });
  doc.moveDown(0.2);
  if (!data.incomes || data.incomes.length === 0) {
    doc.fontSize(12).text('No incomes recorded.');
  } else {
    data.incomes.forEach(i => {
      doc.fontSize(12).text(`${i.source || 'Income'} - ${formatAmount(i.amount)} - ${new Date(i.date).toLocaleDateString()}${i.note ? ' - ' + i.note : ''}`);
    });
  }
  doc.moveDown();

  // Expense list
  doc.fontSize(14).text('Expense List', { underline: true });
  doc.moveDown(0.2);
  if (!data.expenses || data.expenses.length === 0) {
    doc.fontSize(12).text('No expenses recorded.');
  } else {
    data.expenses.forEach(e => {
      doc.fontSize(12).text(`${e.category || 'Expense'} - ${formatAmount(e.amount)} - ${new Date(e.date).toLocaleDateString()}${e.note ? ' - ' + e.note : ''}`);
    });
  }

  doc.moveDown();
  doc.fontSize(10).text('Generated by Budget Planner', { align: 'center' });

  doc.end();
};
